[package]
name = "zero_configure"
version = "0.1.0"
authors = ["Chris Macklin <chris@imaginaryphotons.com>"]

[dependencies]
async-dnssd = "0.3.0"
tokio-core = "*"
futures = "*"
simple-error = "*"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"