[package]

name = "tunnelclient"
version = "0.1.0"
authors = [
    "Chris Macklin <chris.macklin@gmail.com>",
]

[[bin]]
name = "tunnelclient"

[dependencies]
piston_window = "0.105"
piston2d-graphics = "0.35"
pistoncore-glutin_window = "0.63"
piston2d-opengl_graphics = "0.69"
interpolation = "0.2"
yaml-rust = "0.4"
rmp-serde = "0.14.0"
serde = "1"
serde_derive = "1"
streaming-stats = "0.2"
simple-error = "0.2"
zmq = "0.9"
zero_configure = { path = "../zero_configure" }
regex = "1"
lazy_static = "1"
hostname = "0.1"
derive_more = "0.15"
log = "0.4"
simplelog = "0.7"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"
