[package]

name = "tunnelclient"
version = "0.1.0"
authors = [
    "Chris Macklin <chris@imaginaryphotons.com>",
]

[[bin]]
name = "tunnelclient"

[dependencies]
piston = "0.25.0"
piston2d-graphics = "0.17.0"
pistoncore-glutin_window = "0.29.0"
piston2d-opengl_graphics = "0.32.0"
yaml-rust = "*"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"