[package]

name = "tunnelclient"
version = "0.1.0"
authors = [
    "Chris Macklin <chris@imaginaryphotons.com>",
]

[[bin]]
name = "tunnelclient"

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
interpolation = "*"
yaml-rust = "*"
rmp-serde = "*"
serde = "*"
serde_derive = "*"
streaming-stats = "*"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"